version: "3"
services:
  plex:
    container_name: plex
    security_opt:
      - no-new-privileges:true
    image: plexinc/pms-docker:${PLEX_VERSION}
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # - PLEX_CLAIM=claim-<your-string>
      - HOSTNAME="PlexMediaServer"
    volumes:
      - ${HOST_PATH}/plex/config:/config
      - ${HOST_PATH}/plex/transcodes:/transcode
      - ${PLEX_MEDIA_FOLDER}:/media
    networks:
      - frontend

  tautulli:
    container_name: tautulli
    security_opt:
      - no-new-privileges:true
    image: tautulli/tautulli:${TAUTULLI_VERSION}
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8182:8181/tcp
    volumes:
      - ${HOST_PATH}/tautulli:/config
    depends_on:
      - plex
    networks:
      - frontend

networks:
  frontend:
    name: ${FRONTEND_NETWORK}
    external: true
