version: "3"
services:
  nginx-webserver:
    container_name: nginx-webserver
    image: nginx
    environment:
      - TZ=${TZ}
    ports:
        - 8899:80
    volumes:
        - ${HOST_PATH}/simple-webapp/html:/usr/share/nginx/html
    networks:
      - frontend

networks:
  frontend:
    name: ${FRONTEND_NETWORK}
    external: true