---
version: "3"
services:
  bookstack:
    security_opt:
    - no-new-privileges:true
    image: lscr.io/linuxserver/bookstack:${BOOKSTACK_VERSION}
    container_name: bookstackApp
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
    - APP_URL=${BOOKSTACK_APP_URL}
    - DB_HOST=${BOOKSTACK_DB_HOST}
    - DB_USER=${BOOKSTACK_DB_USER}
    - DB_PASS=${BOOKSTACK_DB_PASS}
    - DB_DATABASE=${BOOKSTACK_DB_DATABASE}
    - APP_LANG=en
    # - APP_DEFAULT_DARK_MODE=true
    - FILE_UPLOAD_SIZE_LIMIT=10
    - EXPORT_PAGE_SIZE=a4
    - ALLOW_ROBOTS=null
    - APP_TIMEZONE=${TZ}
    volumes:
    - ${HOST_PATH}/bookstack:/config
    ports:
    - 6875:80
    restart: unless-stopped
    networks:
      - frontend
      - backend

networks:
  frontend:
    name: ${FRONTEND_NETWORK}
    external: true
  backend:
    name: ${BACKEND_NETWORK}
    external: true