version: "3"
services:
  postgres14:
    container_name: postgres14
    security_opt:
      - no-new-privileges:true
    image: registry.hub.docker.com/library/postgres:${POSTGRES_VERSION}
    environment:
      - TZ=${TZ}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    # ports:
    #   - 5432:5432/tcp
    volumes:
      - ${HOST_PATH}/postgres14:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    name: ${BACKEND_NETWORK}
    external: true