version: "3"
services:
  redis:
    container_name: redis
    security_opt:
      - no-new-privileges:true
    image: bitnami/redis:${REDIS_VERSION}
    environment:
      - TZ=${TZ}
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    # ports:
    #   - 6379:6379/tcp
    networks:
      - backend

networks:
  backend:
    name: ${BACKEND_NETWORK}
    external: true
